#!/bin/bash -e
# Addsite
# For use with a lamp stack
# creates a new siteconf, root directory, mysql database/user, hosts entry

sitespath="$HOME/localhost"
apacheuser="www-data"
apachepath="/etc/apache2/sites-available"
apacheskel="000-default.conf"

mysqlpw=""
case "$1" in
    -p|--password)
        mysqlpw="$2"
        shift 2
esac

sitename="$1"
sitepath="$sitespath/$sitename"

if [[
    -z "$sitename" || # If it's empty
    "$sitename" != "$(basename "$sitename")" || # If it's a subfolder
    "$(dirname "$(realpath "$sitepath")")" != "$sitespath" # If it's not under localhost (. .. etc)
]]; then
    >&2 echo "Invalid site '$sitename' offered, aborting"
    exit 1
fi

if [[ -d "$sitepath" || -f "$apachepath/$sitename.conf" ]]; then
    >&2 echo "Site '$sitename' already exists, aborting."
    exit 1
fi

mkdir "$sitepath"
sudo chgrp "$apacheuser" "$sitepath"
cd "$apachepath"
sed -r '
    s:(^|\s+)DocumentRoot '"$sitespath"'$:&/'"$sitename"':
    s:(^|\s+)#ServerName.+$:\1ServerName '"$sitename"'.local:' "$apacheskel" | sudo tee "$sitename.conf" 1>/dev/null
sudo a2ensite "$sitename"
echo -e "127.0.0.1\\t$sitename.local" | sudo tee -a "/etc/hosts" 1>/dev/null
sudo systemctl reload apache2

mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`$sitename\`"
mysql -uroot -e "CREATE USER 'silextest'@'localhost' IDENTIFIED BY '$mysqlpw'";
mysql -uroot -e "GRANT ALL ON \`$sitename\`.* TO '$sitename'@'localhost'"

echo "$sitename created"
