#!/bin/bash
mysql_use_pw=false

if [[ -d "$HOME/localhost/$1" ]]; then
    >&2 echo "'$HOME/localhost/$1' already exists, aborting."
    exit 1
fi

mkdir "$HOME/localhost/$1"
cd "/etc/apache2/sites-available"
sed -r '
    s:(^|\s+)DocumentRoot /home/j/localhost$:&/'"$1"':
    s:(^|\s+)#ServerName.+$:\1ServerName '"$1"'.local:' '000-default.conf' | sudo tee "$1.conf" 1>/dev/null
sudo a2ensite "$1"
echo -e "127.0.0.1\\t$1.local" | sudo tee -a "/etc/hosts" 1>/dev/null
sudo systemctl reload apache2

if [[ "$mysql_use_pw" = "true" ]]; then
    mysqlpw="$(apg -a1 -E "'" -n 1 -m 15 -x 15)"
    mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`$1\`"
    mysql -uroot -e "GRANT ALL ON \`$1\`.* TO '$1'@'localhost' IDENTIFIED BY '$mysqlpw'"
else
    mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`$1\`"
    mysql -uroot -e "GRANT ALL ON \`$1\`.* TO '$1'@'localhost'"
fi

echo "$1 created"

if [[ -v mysqlpw ]]; then
    echo "mysql password is: $mysqlpw"
fi
