#!/bin/bash
# backup
# Sends tarballs the target inside the ~/backup dir

if [[ "$#" -eq 2 ]]; then
    target="$(basename "$(realpath "$2")")"
elif [[ "$#" -eq 1 ]]; then
    target="$(basename "$(realpath "$1")")"
else
    echo "Syntax: backup source [target]"
    exit 1
fi

if [[ ! -e "$1" ]]; then
    echo "Error: File not found"
    exit 1
fi

mkdir -p "$HOME/backup/$target"
tar --force-local -czf "$HOME/backup/$target/$target-$(date '+%F-%T').tar.gz" "$1"
