#!/bin/bash -e
# Delsite
# For use with a lamp stack - deletes a site created with addsite

sitespath="$HOME/localhost"
apachepath="/etc/apache2/sites-available"

sitename="$1"
sitepath="$sitespath/$sitename"

if [[
    -z "$sitename" || # If it's empty
    "$sitename" != "$(basename "$sitename")" || # If it's a subfolder
    "$(dirname "$(realpath -s "$sitepath")")" != "$sitespath" || # If it's not under localhost (. .. etc)
    ! -d "$sitepath" || # If the folder doesn't exist
    ! -f "$apachepath/$sitename.conf" # If the apache config doesn't exist
]]; then
    >&2 echo "Invalid site '$sitename' offered, aborting"
    exit 1
fi

sudo rm -rf "$sitepath"
sudo a2dissite "$sitename"
sudo rm "$apachepath/$sitename.conf"
sudo sed --follow-symlinks -i -r '/^[^#]+'"$sitename"'\.local$/d' "/etc/hosts"
sudo systemctl reload apache2
mysql -uroot -e "DROP DATABASE IF EXISTS \`$sitename\`"
mysql -uroot -e "GRANT USAGE ON *.* TO '$sitename'@'localhost'"
mysql -uroot -e "DROP USER '$sitename'@'localhost'"
echo "$sitename deleted"
