#!/bin/bash
# distanceLevels
# Copies distance levels from workshop to my levels so you can open them in the level editor

cd ~/.config/refract/Distance/Levels/WorkshopLevels &&
rm -rf ../MyLevels/* &&
cp --backup=t */* ../MyLevels/ &&
rename 's/(\.bytes(\.png)?)\.~([0-9]+)~/.$3$1/' ../MyLevels/*
echo -n "Found maps: "
ls ../MyLevels/*.bytes | wc -l
