#!/bin/bash

while [ -n "$1" ]
do
    echo -n "{"

    echo -n "$1" | sed -zr '
        s/((^|[^\])(\\\\)*)\\\n/\1/g        # Eat any escaped newlines
        s/\n/\\n/g                          # Escape the remaining newlines

        s/((^|[^\])(\\\\)*)'\''/\1\\'\''/g  # Escape single quotes

        # GCC character escape sequences are 1-3 octal or unlimited hex numbers.
        # Ive placed no restriction on character escape sequences like \n since
        # I have no idea if there are any compiler-specific ones available.
        s/((\\x[0-9a-fA-F]+)|(\\[0-7]{1,3})|(\\?.))/'\''\1'\'',/g'

    echo "0}"
    shift
done
